{% set name = "trame-markdown" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-markdown-{{ version }}.tar.gz
  sha256: b93d06ba6fa508dcd6982aee2730b6f50b35e92dbbf7b44734eede32e9dfd340

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - trame-client

test:
  imports:
    - trame.widgets.markdown
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-markdown/
  summary: Markdown widget for trame
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
